[2025-02-11 17:46:48] [INFO    ] discord.client: logging in using static token
[2025-02-11 17:46:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9800da17b6dda5569a5e7d86920112e7).
[2025-02-11 18:02:26] [WARNING ] discord.http: We are being rate limited. GET https://discord.com/api/v10/channels/1338250277794349106/pins responded with 429. Retrying in 4.49 seconds.
[2025-02-11 18:02:32] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.03 seconds.
[2025-02-11 18:02:36] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 0.77 seconds.
[2025-02-11 18:02:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:02:38] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.57 seconds.
[2025-02-11 18:02:42] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 1.53 seconds.
[2025-02-11 18:02:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:02:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.78 seconds.
[2025-02-11 18:02:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.59 seconds.
[2025-02-11 18:02:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 2.18 seconds.
[2025-02-11 18:02:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:02:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:02:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:02:50] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.57 seconds.
[2025-02-11 18:02:52] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 2.90 seconds.
[2025-02-11 18:02:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:02:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:02:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:02:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.62 seconds.
[2025-02-11 18:02:57] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 4.55 seconds.
[2025-02-11 18:03:01] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:03:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:03:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:03:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:03:03] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 4.51 seconds.
[2025-02-11 18:03:07] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 762, in on_message
    director = row['Director']
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:03:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.84 seconds.
[2025-02-11 18:03:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:03:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.64 seconds.
[2025-02-11 18:03:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:03:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:03:14] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 4.62 seconds.
[2025-02-11 18:03:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.78 seconds.
[2025-02-11 18:03:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:03:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.61 seconds.
[2025-02-11 18:03:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:03:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:03:26] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 4.60 seconds.
[2025-02-11 18:03:31] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:03:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:03:32] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.57 seconds.
[2025-02-11 18:03:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:03:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.64 seconds.
[2025-02-11 18:03:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:03:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.59 seconds.
[2025-02-11 18:03:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:03:56] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.50 seconds.
[2025-02-11 18:05:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.16 seconds.
[2025-02-11 18:05:12] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 0.43 seconds.
[2025-02-11 18:05:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:05:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.62 seconds.
[2025-02-11 18:05:16] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 2.88 seconds.
[2025-02-11 18:05:18] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 0.37 seconds.
[2025-02-11 18:05:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:05:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:05:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.74 seconds.
[2025-02-11 18:05:21] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.80 seconds.
[2025-02-11 18:05:23] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 364, in apuntar_boton
    await self._manage_check(interaction, not check, msg)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 334, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., El jugador javihu ya está en la lista.
[2025-02-11 18:05:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:05:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:05:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:05:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:05:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:05:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.35 seconds.
[2025-02-11 18:05:37] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 366, in apuntar_boton
    await message.edit(content=event.summarize(), embed=event.to_embed(interaction.user.display_avatar.url))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:05:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:05:44] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 4.52 seconds.
[2025-02-11 18:05:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.23 seconds.
[2025-02-11 18:05:50] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.02 seconds.
[2025-02-11 18:05:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:05:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:05:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.68 seconds.
[2025-02-11 18:06:00] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 0.63 seconds.
[2025-02-11 18:06:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.84 seconds.
[2025-02-11 18:06:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:06:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:06:02] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 4.46 seconds.
[2025-02-11 18:06:06] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 1.09 seconds.
[2025-02-11 18:06:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:06:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 0.30 seconds.
[2025-02-11 18:06:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:06:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:06:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338624101991845949 responded with 429. Retrying in 5.29 seconds.
[2025-02-11 18:06:08] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 4.43 seconds.
[2025-02-11 18:06:13] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:06:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 0.30 seconds.
[2025-02-11 18:06:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:06:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:06:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:06:13] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.
[2025-02-11 18:06:16] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 2.77 seconds.
[2025-02-11 18:06:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:06:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:06:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.72 seconds.
[2025-02-11 18:06:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.64 seconds.
[2025-02-11 18:06:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:06:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:06:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:06:26] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 4.62 seconds.
[2025-02-11 18:06:31] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:06:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:06:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.78 seconds.
[2025-02-11 18:06:31] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.59 seconds.
[2025-02-11 18:06:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.84 seconds.
[2025-02-11 18:06:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:06:38] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 4.68 seconds.
[2025-02-11 18:06:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:06:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:06:43] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.64 seconds.
[2025-02-11 18:06:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 1.55 seconds.
[2025-02-11 18:06:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:06:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:06:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:06:49] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.62 seconds.
[2025-02-11 18:06:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.83 seconds.
[2025-02-11 18:06:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:06:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.65 seconds.
[2025-02-11 18:06:56] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:07:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:07:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:07:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.63 seconds.
[2025-02-11 18:07:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:07:07] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.62 seconds.
[2025-02-11 18:07:08] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 4.59 seconds.
[2025-02-11 18:07:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:07:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.61 seconds.
[2025-02-11 18:07:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.61 seconds.
[2025-02-11 18:07:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:07:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.70 seconds.
[2025-02-11 18:07:25] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:07:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.59 seconds.
[2025-02-11 18:09:03] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 364, in apuntar_boton
    await self._manage_check(interaction, not check, msg)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 334, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., El jugador javihu ya está en la lista.
[2025-02-11 18:09:24] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.24 seconds.
[2025-02-11 18:09:24] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 4.50 seconds.
[2025-02-11 18:09:26] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Quitarme' emoji=<PartialEmoji animated=False name='❌' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 385, in quitar_boton
    await self._manage_check(interaction, not check, msg)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 334, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., El jugador javihu no está en la lista.
[2025-02-11 18:09:29] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 364, in apuntar_boton
    await self._manage_check(interaction, not check, msg)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 334, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., El jugador javihu ya está en la lista.
[2025-02-11 18:09:29] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:09:29] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.62 seconds.
[2025-02-11 18:09:30] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 4.76 seconds.
[2025-02-11 18:09:32] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.13 seconds.
[2025-02-11 18:09:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:09:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:09:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:09:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.69 seconds.
[2025-02-11 18:09:37] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 3.61 seconds.
[2025-02-11 18:09:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.84 seconds.
[2025-02-11 18:09:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.84 seconds.
[2025-02-11 18:09:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:09:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:09:42] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 4.55 seconds.
[2025-02-11 18:09:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 0.30 seconds.
[2025-02-11 18:09:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:09:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:09:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:09:48] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 0.38 seconds.
[2025-02-11 18:09:48] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.36 seconds.
[2025-02-11 18:09:48] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 4.63 seconds.
[2025-02-11 18:09:53] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 366, in apuntar_boton
    await message.edit(content=event.summarize(), embed=event.to_embed(interaction.user.display_avatar.url))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:09:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:09:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:09:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:09:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.63 seconds.
[2025-02-11 18:09:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 3.60 seconds.
[2025-02-11 18:09:59] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Quitarme' emoji=<PartialEmoji animated=False name='❌' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 387, in quitar_boton
    await message.edit(content=event.summarize(), embed=event.to_embed(interaction.user.display_avatar.url))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:09:59] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:09:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:09:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:09:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.78 seconds.
[2025-02-11 18:09:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:10:00] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 4.61 seconds.
[2025-02-11 18:10:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 0.30 seconds.
[2025-02-11 18:10:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:10:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:10:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:10:05] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.
[2025-02-11 18:10:06] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 4.60 seconds.
[2025-02-11 18:10:06] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 4.50 seconds.
[2025-02-11 18:10:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.81 seconds.
[2025-02-11 18:10:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:10:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:10:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:10:13] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.60 seconds.
[2025-02-11 18:10:17] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:10:17] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:10:17] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:10:17] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.71 seconds.
[2025-02-11 18:10:19] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.59 seconds.
[2025-02-11 18:10:23] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:10:23] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:10:23] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:10:23] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:10:24] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 4.55 seconds.
[2025-02-11 18:10:29] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:10:29] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:10:29] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.80 seconds.
[2025-02-11 18:10:29] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.60 seconds.
[2025-02-11 18:10:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.78 seconds.
[2025-02-11 18:10:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.74 seconds.
[2025-02-11 18:10:38] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 2.52 seconds.
[2025-02-11 18:10:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:10:41] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:10:42] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.08 seconds.
[2025-02-11 18:10:42] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 4.44 seconds.
[2025-02-11 18:10:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.70 seconds.
[2025-02-11 18:10:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.69 seconds.
[2025-02-11 18:10:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.64 seconds.
[2025-02-11 18:10:47] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.46 seconds.
[2025-02-11 18:10:51] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 1.92 seconds.
[2025-02-11 18:10:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:10:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:10:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:10:53] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.72 seconds.
[2025-02-11 18:10:55] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 3.35 seconds.
[2025-02-11 18:10:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.83 seconds.
[2025-02-11 18:10:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:10:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:10:59] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.74 seconds.
[2025-02-11 18:11:01] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 3.57 seconds.
[2025-02-11 18:11:05] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Anular (Solo directores)' emoji=<PartialEmoji animated=False name='💀' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 408, in anular_boton
    await message.edit(view=None)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:11:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.83 seconds.
[2025-02-11 18:11:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 5.79 seconds.
[2025-02-11 18:11:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.77 seconds.
[2025-02-11 18:11:05] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338622262642872492 responded with 429. Retrying in 5.75 seconds.
[2025-02-11 18:11:11] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 823, in on_message
    await msg.edit(view=EventsButton(database=self.database))
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:11:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.82 seconds.
[2025-02-11 18:11:11] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.76 seconds.
[2025-02-11 18:11:15] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 1.67 seconds.
[2025-02-11 18:11:17] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Anular (Solo directores)' emoji=<PartialEmoji animated=False name='💀' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 408, in anular_boton
    await message.edit(view=None)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\message.py", line 2086, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 30046): Maximum number of edits to messages older than 1 hour reached.
[2025-02-11 18:11:17] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 5.73 seconds.
[2025-02-11 18:11:25] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338618357599178834 responded with 429. Retrying in 3.80 seconds.
[2025-02-11 18:11:32] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338615446324248708 responded with 429. Retrying in 3.06 seconds.
[2025-02-11 18:11:33] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 1.80 seconds.
[2025-02-11 18:11:35] [WARNING ] discord.http: We are being rate limited. PATCH https://discord.com/api/v10/channels/1338250277794349106/messages/1338621843468325009 responded with 429. Retrying in 5.71 seconds.
[2025-02-11 18:13:25] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command sync
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 978, in invoke
    await self.prepare(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 882, in prepare
    if not await self.can_run(ctx):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\utils.py", line 660, in async_all
    for elem in gen:
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 2006, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 'administrador' is required to run this command.
[2025-02-11 18:13:31] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command reload
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 978, in invoke
    await self.prepare(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 882, in prepare
    if not await self.can_run(ctx):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\utils.py", line 660, in async_all
    for elem in gen:
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 2006, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 'administrador' is required to run this command.
[2025-02-11 18:13:33] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command sync
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 978, in invoke
    await self.prepare(ctx)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 882, in prepare
    if not await self.can_run(ctx):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\utils.py", line 660, in async_all
    for elem in gen:
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 1243, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\commands\core.py", line 2006, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 'administrador' is required to run this command.
[2025-02-11 18:27:13] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "reaload" is not found
[2025-02-11 18:27:37] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 364, in apuntar_boton
    else:
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 334, in _manage_check
    def is_eq_id(self, id):
AssertionError:  <EVENTOS> Error..., El jugador javihu ya está en la lista.
[2025-02-11 18:28:03] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Apuntarme' emoji=<PartialEmoji animated=False name='✔️' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 404, in apuntar_boton
    await _manage_check(interaction, not check, msg)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 349, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., El jugador javihu (Polizón) ya está en la lista.
[2025-02-11 18:56:14] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'crear'
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 850, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 536, in crear
    embed=event.to_embed(interaction),
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 313, in to_embed
    icon_guild = interaction.guild.icon.url
AttributeError: 'NoneType' object has no attribute 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'crear' raised an exception: AttributeError: 'NoneType' object has no attribute 'url'
[2025-02-11 19:01:08] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Anular (Solo directores)' emoji=<PartialEmoji animated=False name='💀' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 441, in anular_boton
    await _manage_check(interaction,
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 354, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., No eres el director del evento **nuevas**.
[2025-02-11 19:02:18] [ERROR   ] discord.ui.view: Ignoring exception in view <EventsButton timeout=180 children=3> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Anular (Solo directores)' emoji=<PartialEmoji animated=False name='💀' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 441, in anular_boton
    await _manage_check(interaction, not check, event)
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 354, in _manage_check
AssertionError:  <EVENTOS> Error..., No eres el director del evento **nuevas**.
[2025-02-11 19:08:06] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'modificar'
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 850, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 721, in modificar
    await _manage_check(interaction,
  File "F:\Proyectos\BotBukanerosV2\bot-bukaneros\bot\cogs\eventos.py", line 355, in _manage_check
    assert not check, f' <EVENTOS> Error..., {msg}'
AssertionError:  <EVENTOS> Error..., No eres el director del evento **UltimaPrueba**.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'modificar' raised an exception: AssertionError:  <EVENTOS> Error..., No eres el director del evento **UltimaPrueba**.
[2025-02-11 19:11:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9800da17b6dda5569a5e7d86920112e7.
[2025-02-11 19:30:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9800da17b6dda5569a5e7d86920112e7.
[2025-02-11 19:53:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9800da17b6dda5569a5e7d86920112e7.
[2025-02-11 22:44:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 9800da17b6dda5569a5e7d86920112e7.
